//Types to identify redux actions
export const CHARACTERS_UPDATE_LIST = "CHARACTERS_UPDATE_LIST"
export const CHARACTERS_SELECTED = "CHARACTERS_SELECTED"
export const CHARACTERS_SET_FETCHING = "CHARACTERS_SET_FETCHING"